# amd64
FROM canal/osbase:v3-amd64@sha256:2b1557d9fc14471fc39e5a398cefcd5d7e2777ab743dc29d467822aa883f8127

MAINTAINER agapple (jianghang115@gmail.com)

RUN \
    groupadd -r mysql && useradd -r -g mysql mysql && \
    wget https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm  && \
    rpm -ivh mysql80-community-release-el7-3.noarch.rpm  && \
    yum install sudo mysql-community-server --nogpgcheck -y && \
    rm -f mysql80-community-release-el7-3.noarch.rpm && \
    yum clean all && \
    true

CMD ["/bin/bash"]
