name: test

on: [pull_request_target]

permissions:
  contents: read

jobs:
  _:
    name: "Require “Allow Edits”"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
